version: '3'

services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/covid
      SPRING_DATASOURCE_USERNAME: covid
      SPRING_DATASOURCE_PASSWORD: covid
  
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: covid
      POSTGRES_USER: covid
      POSTGRES_PASSWORD: covid
      interval: 30s
      timeout: 30s
      retries: 2

    
    
