GET http://localhost:8080/api/public/centers?city=N%

//GET http://localhost:4200/api/public/centers?city=M%
//Accept: text/html
//le % permet de sélectionner tout qui commence par un N, si on l'avait mis avant on aurait villers les nancy par ex