spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://database:5432/covid
    username: covid
    password: covid
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update

    #le mettre en commentaires si il y a des données dans la bdd

